name: Send Daily Quote

on:
  schedule:
    - cron: '0 3 * * *'  # Runs daily at 03:00 UTC
  workflow_dispatch:      # Allows manual trigger
    inputs:
      refresh_window_months:
        description: 'Number of months to refresh quotes'
        required: false
        default: 3

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Set Job Variables
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ -n "${{ github.event.inputs.refresh_window_months }}" ]; then
            echo "REFRESH_WINDOW_MONTHS=${{ github.event.inputs.refresh_window_months }}" >> $GITHUB_ENV
          else
            echo "REFRESH_WINDOW_MONTHS=${{ vars.REFRESH_WINDOW_MONTHS }}" >> $GITHUB_ENV
          fi
      - name: Run script
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DB_ID: ${{ secrets.NOTION_DB_ID }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: |
          echo "Running script"
          echo 
          echo "ENVS:"
          echo "  REFRESH_WINDOW_MONTHS=${REFRESH_WINDOW_MONTHS}"
          echo
          python main.py --refresh_window_months $REFRESH_WINDOW_MONTHS
